---
- name: playbook de configuration du host pour le site web
  hosts: monsiteweb
  remote_user: azureuser
  become: yes
  tasks:
    - name: Copy a Dockerfil file on the remote machine
      copy:
        src: "{{dockerfile_path}}/Dockerfile"
        dest: /tmp/Dockerfile
        remote_src: yes
    - name: Build image using cache source
      command: "docker build --no-cache -f tmp/Dockerfile -t monsiteweb_image ."
    - name: Stop a container
      docker_container:
        name: monsiteweb
        state: stopped
    - name: remove container
      docker_container:
        name: monsiteweb
        state: absent
    - name: Restart a container
      docker_container:
        name: monsiteweb
        image: monsiteweb_image
        state: started
        ports:
        - "8080:80"