---
- name: playbook de configuration du host pour le site web
  hosts: monsiteweb
  remote_user: azureuser
  become: yes
  tasks:
    - name: installation of docker collection
      command: ansible-galaxy collection install community.docker 
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: clean
      command: yum clean all
    - package:
        name: "{{ item}}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - git
        - docker
    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
